# Generated by Django 4.1.7 on 2023-03-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_added_phone_sheets_validator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='count',
            new_name='quantity',
        ),
    ]
